// Generated for: AsposePdfLib 1.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.4.0.0
/* eslint-disable */

const dotnet = require('node-api-dotnet');
const path = require('node:path');

const assemblyName = path.basename(__filename, '.js');
const assemblyFilePath = path.join(__dirname, assemblyName + '.dll');
dotnet.load(assemblyFilePath);
